### ISSUE TITLE
where is config files?

### ISSUE THREAD

**Issue by mani-nemati** [fruithost/Panel#10]
i got this massage:

The host "cp.domain.com" is currently not configured.

and 
where is config files?

**Comment by Bizarrus** [comment]
You can found a structure of the file system on the Docs:
[https://github.com/fruithost/Documentation/blob/main/Structure.md](https://github.com/fruithost/Documentation/blob/main/Structure.md)

The Files of a host is in `/var/fruithost/users/<username>/<domain>/`

When the message appears, that an host is not configured, the domain will pointed to the placeholder (`/etc/fruithost/placeholder`).
You must add a Domain/Host in the MySQL database. When your deamon-process is working normally, domains will be created automatically when you insert it to the database.

Otherwise look up the shell commands ([https://github.com/fruithost/Binary](https://github.com/fruithost/Binary)) and try to execute the command
> fruithost daemon
