### ISSUE TITLE
[Help] Modules missing after installation

### ISSUE THREAD

**Issue by konstantinosbotonakis** [fruithost/Panel#15]
### Question

Running the automatic installation, I can't see to be able to see the modules installed, neither I get an error when installing.
Couldn't find a guide on how to install modules that exist already afterwards. 

Is it something to be implemented?

**Comment by Bizarrus** [comment]
In the beginning the `/modules` folder was done by a `git clone` of the module repository.

However, I decided to remove this from the regular installation process, as each module has to be installed individually.

The standard repository is already included under `http://<panel-domain>/admin/modules/repositorys`. You only need to install the modules you want to install manually:
> fruithost install domains
as an example.

After installation you must enable the module:
> fruithost enable domains

Here is the complete command palette (type only `fruithost` on shell):
![image](https://github.com/fruithost/Panel/assets/1371300/73e3db3a-ddb7-4412-9ee1-b3e419d1c3c5)

**Comment by konstantinosbotonakis** [comment]
As we have a specific structure for modules, are you planning to be able to upload modules from the panel?
If not, are you happy for me to develop that?
And at last, is there any way of communication, new feature requests so I can contribute more?

**Comment by konstantinosbotonakis** [comment]
> Here is the complete command palette (type only fruithost on shell):

Can you add this in the docs please? Very useful.

**Comment by Bizarrus** [comment]
This informations already in the Daemon-description - i will port it to the docs:
https://github.com/fruithost/Binary

There is currently only a to-do list in my head, as I am relatively quick at implementing it. But we can keep one. Perhaps we can create a changelog as well as a to-do list in the `Documnetation` repository?

An upload directly from the panel should also be supported later, but currently has limitations: Execute and write permissions.

An upload via the panel must therefore do the following:
Download the module package (`<repository-url>/module.package/<name>.zip`) into the `/temp` folder and an extra database table so that the installation can be processed via the daemon. The daemon must also be adapted for this. It was also planned to use PHP's own progressbars for a panel upload.

**Comment by konstantinosbotonakis** [comment]
> An upload via the panel must therefore do the following:
Download the module package (<repository-url>/module.package/<name>.zip) into the /temp folder and an extra database table so that the installation can be processed via the daemon. The daemon must also be adapted for this. It was also planned to use PHP's own progressbars for a panel upload.

I agree.

> There is currently only a to-do list in my head, as I am relatively quick at implementing it. But we can keep one. Perhaps we can create a changelog as well as a to-do list in the Documnetation repository?

That would be great so also other users can contribute if they know what's needed.

I have some PRs ready to be pushed regarding Data Validation in Account Settings and other pages. I know there are plans to update everything, but let's have a base line of improvements if possible.

**Comment by Bizarrus** [comment]
> I have some PRs ready to be pushed regarding Data Validation in Account Settings and other pages. I know there are plans to update everything, but let's have a base line of improvements if possible.
You are welcome to conduct PRs at any time.

I am currently working on the banch `bootstrap-5` to upgrade to **Bootstrap 5**, here I have already made some improvements. With the panel I am almost finished with the bootstrap update, here are still missing adjustments of the modules

**Comment by Bizarrus** [comment]
https://github.com/fruithost/Documentation/blob/main/System/ToDo.md
