### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by arqbyte** [fruithost/Panel#8]
Does this panel have an api?

**Comment by Bizarrus** [comment]
Hey,

the last development step was 4 years ago. The panel has not been fully developed. Estimated I have implemented only 60% of the functions/methods.

The panel should also get a JSON API, because at a later stage things should be reloaded via Ajax, but this is not implemented yet.

**Comment by arqbyte** [comment]
Hi,

I want to make a client area for a webhosting control panel in PHP, but all the ones I have found there is no way of blocking users from creating sites and dbs on there. Since I am making the client area with coins earning and users have to earn resources. 

Is it possible you can refer me one?

**Comment by Bizarrus** [comment]
You want a reward system that can unlock features to use?

Would be possible in principle, but I haven't touched anything on fruithost for 4 years. The whole system works with the basics, but is not yet ready for productive use. There are still some functions missing.

I also don't know if and when I will develop fruithost further.

**Comment by arqbyte** [comment]
I want to make a client area for a webhosting panel, in the client area I will have coins earning methods such as afk, linkvertise. But all the panel I have seen so far does not have permission because I don't want to let the user create a website on the panel, I want it on the client area.

**Comment by Bizarrus** [comment]
They confuse how it works and where it is used. A hosting panel is intended exclusively for server architecture administration.
With your info, it is also explicitly not apparent which scenario you need, as your statements are very vague and squishy.

Either yours sounds like a so called reseller program or an application specific request that can be realized with various content management systems like WordPress (or similar).

Your problem seems to have special requirement that can certainly be implemented with common open source solutions, but is not usable for the general public.

I therefore ask you to look for a web agency and commission your individual project.

**Comment by arqbyte** [comment]
Ok, thank you
